import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const developmentPreviewMeta =
  /<meta(?=[^>]*\bname=["']codex-preview["'])(?=[^>]*\bcontent=["']development["'])[^>]*>/i;

test("renders development preview metadata", async () => {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  const response = await worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );

  assert.equal(response.status, 200);
  assert.match(
    response.headers.get("content-type") ?? "",
    /^text\/html\b/i,
  );
  assert.match(await response.text(), developmentPreviewMeta);
});

test("editing a legacy waybill is not blocked by newly required fields", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

  assert.match(source, /if \(!existing && !rawAppliedDate\)/);
  assert.match(source, /if \(!existing && rawTotalWeightG === ""\)/);
  assert.match(source, /if \(!existing && rawFreightTwd === ""\)/);
  assert.match(source, /rawArrivedDate \|\| dateInputValue\(existing\?\.arrivedDate\) \|\| todayInputValue\(\)/);
});

test("saving a waybill updates local state and lets the shared cloud sync persist it", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const saveWaybill = source.slice(
    source.indexOf("function saveWaybill"),
    source.indexOf("if (!authChecked"),
  );

  assert.match(saveWaybill, /setGroups\(nextGroups\)/);
  assert.match(saveWaybill, /setWaybills\(nextWaybills\)/);
  assert.doesNotMatch(saveWaybill, /await updateDoc/);
});

test("waybill order weight keeps numeric zero instead of rendering it as blank", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

  assert.match(source, /value=\{value\.weightG\}/);
  assert.doesNotMatch(source, /value=\{value\.weightG\|\|""\}/);
});

test("all admin changes are backed up locally before cloud persistence", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(source, /localStorage\.setItem\(localStateKey/);
  assert.match(source, /JSON\.stringify\(\{ \.\.\.state, savedAt \}\)/);
  assert.match(source, /local\.savedAt > firestoreMillis\(remote\.updatedAt\)/);
});

test("admin cloud persistence uses the authenticated sync service with a timeout", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(source, /requestWithTimeout\(`\$\{friendAuthApi\}\/admin\/sync`/);
  assert.match(source, /getIdToken\(\)/);
  assert.doesNotMatch(source, /setDoc\(doc\(db, "admin", "state"\)/);
});

test("friend views are generated by the trusted worker instead of forbidden browser writes", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.doesNotMatch(source, /setDoc\(doc\(db, "friendViews"/);
  const worker = await readFile(new URL("../friend-auth-worker/src/index.ts", import.meta.url), "utf8");
  assert.match(worker, /friendViewsFromState/);
  assert.match(worker, /url\.pathname === "\/admin\/sync"/);
  assert.match(worker, /documents:commit/);
});

test("cloud writes are serialized and expose their real result", async () => {
  const source = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(source, /cloudSaveQueue\.current = cloudSaveQueue\.current/);
  assert.match(source, /setCloudSaveState\("saved"\)/);
  assert.match(source, /setCloudSaveState\("error"\)/);
  assert.match(source, /已儲存至雲端/);
  assert.match(source, /僅存於本機/);
});
